num1 = int(input("Ingresa el 1er numero: "))
num2 = int(input("Ingresa el 2do numero: "))
num3 = int(input("Ingresa el 3ro numero: "))
print("la suma de los 3 numeros:")
print(num1 + num2 + num3)
print("la resta de los 3 numeros:")
print(num1 - num2 - num3)
print("la division de los 3 numeros:")
print(num1 / num2 / num3)
print("la multiplicacion de los 3 numeros:")
print(num1 * num2 * num3)
print(type(num1))
print(type(num2))
print(type(num3))
print(num1)
print(num2)
print(num3)